name: Maven Build 

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@1
        with:
          java-version: 1.8
          
      - name: Build with maven
        run: mvn -B package --file pom.xml
        
      - name: List the current directory
        run: ls -a
        
      - name: Target Folder
        run: |
          cd target
          ls -a
          
       
